
#' karate graph
#'
#' Graph with  nodes from 
#'
#' @format igraph object
#' @source \url{http://www-personal.umich.edu/~mejn/netdata/}
"karate"

#' celegans graph
#'
#' Graph with  nodes from 
#'
#' @format igraph object
#' @source \url{http://www-personal.umich.edu/~mejn/netdata/}
"celegans"

#' polblogs graph
#'
#' Graph with  nodes from 
#'
#' @format igraph object
#' @source \url{http://www-personal.umich.edu/~mejn/netdata/}
"polblogs"



#' yeast graph
#'
#' Graph with  nodes from 
#'
#' @format igraph object
#' @source \url{https://www.nature.com/articles/nature750}
"yeast"



#' arxiv graph
#'
#' Graph with  nodes from 
#'
#' @format igraph object
#' @source \url{http://www-personal.umich.edu/~mejn/netdata/}
"arxiv"




#' @rdname Simulations
#' 
#' @title Simulation results from the paper.
#'
#' @description Results from the different simulations to remake the plots. 
#'  Each is a list of data frames.
#'
#' @source Generated by code from this package.
"parsim_er"

#' @rdname Simulations
#'
"parsim_ws"

#' @rdname Simulations
#'
"parsim5"

#' @rdname Simulations
#'
"parsim50"


#' @rdname Realdata
#' 
#' @title Real data simulations results.
#' @description Results from the different simulations to remake the plots. 
#'  realnet_error_df has results from corrupting and graph matching.
#'  disag_data has results from permuting and computing disagreements.
#'
#' @source Generated by code from this package.
"realnet_error_df"

#' @rdname Realdata
#' 
"disag_data"
